### ISSUE TITLE
(1.17 fabric beta) HUD won't change positions and random mobs are nearly invisible besides little strands of rgb on the head

### ISSUE THREAD

**Issue by Shakazu** [ToroCraft/ToroHealth#102] opened 2021-06-28 13:26 UTC
I'm fairly certain I have fucked something up seeing as I am not so experienced with modding and I haven't seen any other similar issue reports but, I un/reinstalled and still had the same issues. The invisible mobs would return to normal on changing the inWorld.mode back to NONE. When setting onlyWhenLookingAt and onlyWhenHurt to true, the invisibility would pop up again. I didn't experiment with too many mobs, but the invisibility only seemed to affect cows and zombies. For the benefit of maybe being asked, I have fabric-loader-0.11.6-1.17, fabric-api-0.36.0+1.17, optifabric-1.11.9, preview_Optifine_1.17_HD_U_G9_pre24, Xaeros_Minimap_21.12.2_Fabric_1.17, and Xaeros_WorldMap_1.14.4_Fabric_1.17 installed. No resource packs or anything that I would assume to cause an issue. 

As for the HUD, works great on default settings. When I attempt to change the location the HUD disappears save for the mob model, which stays in the default placement. I also moved the minimap around just in case that might have caused interference.

If there is anything else I could attempt to provide, or if I just botched something, lmk

**Comment by frodare** [comment] 2021-06-30 16:34
I think this is caused by a bug in the release for 1.17. I am going to be working on the next release soon which will hopefully fix these issues.  Thanks for letting me know.

**Comment by frodare** [comment] 2021-07-01 02:04
I think this issue is the same as #103, please subscribe to that one keep updated.  The entity location should fixed as of torohealth-1.17-fabric-6.jar.

**Closed by frodare** 2021-07-01 02:04 UTC
